version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers
        environment:
          RAILS_ENV: test

commands:
  install_deps:
    description: install bundle
    steps:
      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}
            - dependencies-
      - run: |
          sudo apt-get install cmake
          gem install bundler -v 2.2.22
          bundle config set path vendor/bundle
          bundle install --jobs=4 --retry=3
      - save_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  run_rspec:
    description: "run rspec command"
    steps:
      - run:
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          command: |
            bundle exec rspec \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split)
      - store_test_results:
          path: test_results
      - run:
          name: Store coverage report
          command: |
            mkdir -p /tmp/coverage
            mv coverage/lcov/*.lcov /tmp/coverage/
            mv coverage/.resultset.json "/tmp/coverage/.resultset-${CIRCLE_NODE_INDEX}.json"
      - persist_to_workspace:
          root: /tmp/coverage
          paths: .
      - store_artifacts:
          path: /tmp/coverage
          destination: coverage

references:
  attach_workspace: &attach_workspace
    at: ~/project

jobs:
  setup:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - install_deps

  test_backend:
    executor: my-executor
    parallelism: 2
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - install_deps
      - run_rspec
      - store_test_results:
            path: tmp/test-results

  analyse_coverage:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/coverage
      - install_deps
      - run:
          name: concat lcov files to handle pronto-undercover
          command: |
            mkdir -p coverage/lcov
            cat /tmp/coverage/*.lcov > coverage/lcov/coverage_default.lcov
      - run:
          name: run pronto
          command: |
            bundle exec pronto run -r undercover -f github_pr -c origin/master

  report_coverage:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/coverage
      - install_deps
      - run:
          name: generate coverage report
          command: |
            bundle exec ruby -e "require 'simplecov'; SimpleCov.collate Dir['/tmp/coverage/.resultset*.json'], 'rails'"
      - store_artifacts:
          path: coverage

workflows:
  build:
    jobs:
      - setup
      - test_backend:
          requires:
            - setup
      - analyse_coverage:
          requires:
            - test_backend
          filters:
            branches:
              ignore: master
      - report_coverage:
          requires:
            - test_backend
