version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers
        environment:
          RAILS_ENV: test

commands:
  install_deps:
    description: install bundle
    steps:
      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}
            - dependencies-
      - run: |
          gem install bundler -v 2.2.22
          bundle config set path vendor/bundle
          bundle install --jobs=4 --retry=3
      - save_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  run_rspec:
    description: "run rspec command"
    steps:
      - run:
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          command: |
            bundle exec rspec \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split)
      - store_test_results:
          path: test_results

references:
  attach_workspace: &attach_workspace
    at: ~/project

jobs:
  setup:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - install_deps

  test_backend:
    executor: my-executor
    parallelism: 2
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - install_deps
      - run_rspec
      - store_test_results:
            path: tmp/test-results

workflows:
  build:
    jobs:
      - setup
      - test_backend:
          requires:
            - setup
